<option value="Betriebswirtschaftslehre (BWL)">Betriebswirtschaftslehre (BWL)</option>
<option value="Allgemeine Volkswirtschaft">Allgemeine Volkswirtschaft</option>
<option value="Management">Management</option>
<option value="Sportökonomie">Sportökonomie</option>
<option value="Wirtschaftspsychologie">Wirtschaftspsychologie</option>
<option value="Wirtschaftsingenieurwesen">Wirtschaftsingenieurwesen</option>
<option value="Marketing">Marketing</option>
<option value="Rechtsgeschichte">Rechtsgeschichte</option>
<option value="Handelsrecht">Handelsrecht</option>
<option value="Strafrecht">Strafrecht</option>
<option value="Arbeitsrecht">Arbeitsrecht</option>
<option value="Steuerrecht">Steuerrecht</option>
<option value="Familienrecht">Familienrecht</option>
<option value="Wirtschaftsrecht">Wirtschaftsrecht</option>
<option value="Herkunft von Sprachen">Herkunft von Sprachen</option>
<option value="Entwicklung von Sprachen">Entwicklung von Sprachen</option>
<option value="Bestandteile von Sprachen">Bestandteile von Sprachen</option>
<option value="Einheiten von Sprachen">Einheiten von Sprachen</option>
<option value="Kommunikation, Wahrnehmung">Kommunikation, Wahrnehmung</option>
<option value="Semantik">Semantik</option>
<option value="Sprachvergleich, Sprachsysteme">Sprachvergleich, Sprachsysteme</option>
<option value="Dialektologie">Dialektologie</option>
<option value="Lexikologie">Lexikologie</option>
<option value="Linguistik des Textes">Linguistik des Textes</option>
<option value="Literaturwissenschaft">Literaturwissenschaft</option>
<option value="Bibliothekswissenschaft">Bibliothekswissenschaft</option>
<option value="Soziolinguistik">Soziolinguistik</option>
<option value="Philologie">Philologie</option>
<option value="Politische Institutionen">Politische Institutionen</option>
<option value="Sprachwissenschaft">Sprachwissenschaft</option>
<option value="Pharmazie">Pharmazie</option>
<option value="Anatomie">Anatomie</option>
<option value="Anästhesiologie">Anästhesiologie</option>
<option value="Chirurgie">Chirurgie</option>
<option value="Gesundheitswissenschaft">Gesundheitswissenschaft</option>
<option value="Humanmedizin">Humanmedizin</option>
<option value="Kinder- und Jugendmedizin">Kinder- und Jugendmedizin</option>
<option value="Hygiene- und Umweltmedizin">Hygiene- und Umweltmedizin</option>
<option value="Neurologie">Neurologie</option>
<option value="Pathologie">Pathologie</option>
<option value="Gesundheitsmanagement">Gesundheitsmanagement</option>
<option value="Physiologie">Physiologie</option>
<option value="Pflegewissenschaften">Pflegewissenschaften</option>
<option value="Orthopädie">Orthopädie</option>
<option value="Vorschul-Pädagogik">Vorschul-Pädagogik</option>
<option value="Geschichte der Pädagogik">Geschichte der Pädagogik</option>
<option value="Logopädie">Logopädie</option>
<option value="Methodik des Unterrichts">Methodik des Unterrichts</option>
<option value="Pädagogische Innovation">Pädagogische Innovation</option>
<option value="Sozialpädagogik">Sozialpädagogik</option>
<option value="Sonderpädagogik">Sonderpädagogik</option>
<option value="Vergleichende Pädagogik">Vergleichende Pädagogik</option>
<option value="Taubstummenpädagogik">Taubstummenpädagogik</option>
<option value="Erziehungstheorie">Erziehungstheorie</option>
<option value="Schulbildung">Schulbildung</option>
<option value="Blindenpädagogik">Blindenpädagogik</option>
<option value="Sehbehindertenpädagogik">Sehbehindertenpädagogik</option>
<option value="Didaktik">Didaktik</option>
<option value="Andere">Andere</option>