<input type="hidden" name="fc_campaign">
<input type="hidden" name="fc_channel">
<input type="hidden" name="fc_content">
<input type="hidden" name="fc_landing">
<input type="hidden" name="fc_medium">
<input type="hidden" name="fc_referrer">
<input type="hidden" name="fc_source">
<input type="hidden" name="fc_term">
<input type="hidden" name="lc_campaign">
<input type="hidden" name="lc_channel">
<input type="hidden" name="lc_content">
<input type="hidden" name="lc_landing">
<input type="hidden" name="lc_medium">
<input type="hidden" name="lc_referrer">
<input type="hidden" name="lc_source">
<input type="hidden" name="lc_term">
<input type="hidden" name="OS">
<input type="hidden" name="GA_Client_ID">
<input type="hidden" name="gclid">
<input type="hidden" name="all_traffic_sources">
<input type="hidden" name="browser">
<input type="hidden" name="city">
<input type="hidden" id="country">
<input type="hidden" id="device">
<input type="hidden" id="page_visits">
<input type="hidden" id="pages_visited_list">
<input type="hidden" id="region">
<input type="hidden" id="time_zone">
<input type="hidden" id="time_passed">
<input type="hidden" id="latitude">
<input type="hidden" id="longitude">